name: Build and deploy Angular app to Azure Storage Account

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build -- --prod
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: todo-angular-${{ github.run_id }}
          path: ./dist/todo-ui
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI Action
        uses: Azure/cli@1.0.4
        with:
          inlineScript: az storage blob upload-batch --account-name stgodsidptodoui -d '$web' -s ./dist/todo-ui
      - name: Azure logout
        run: |
          az logout
